\LoadClass[14pt,a4paper]{extreport}
%\documentclass[graybox,envcountchap]{SVMonoEnhanced}
\usepackage{type1cm}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[russian,english]{babel}
\usepackage{hyperref}
\usepackage[table,xcdraw]{xcolor}

\usepackage[none]{hyphenat}
\usepackage{amssymb,amscd, amsmath, amsfonts, amssymb, newtxtext,newtxmath}
\usepackage{makeidx, graphicx}
\usepackage[bottom]{footmisc}
\usepackage{parskip}
\usepackage{setspace}
\usepackage{stackengine}
\usepackage[margin=2.4cm]{geometry}
%\usepackage{fancyhdr}

%\pagestyle{fancy}
%\renewcommand{\sectionmark}[1]{\markright{\thesection~ #1}}
%\renewcommand{\chaptermark}[1]{\markboth{\thechapter~ #1}{}}
%
%\fancyhead[LO]{\rightmark}
%\fancyhead[RE]{\leftmark}
%\fancyhead[LE,RO]{\thepage}
%\renewcommand{\headrulewidth}{0pt}

%\usepackage{vmargin}
%\setmarginsrb{3 cm}{2.4 cm}{3 cm}{2.4 cm}{1 cm}{1.5 cm}{1 cm}{1.5 cm}



%\renewcommand{\baselinestretch}{1.25}
\newcommand\xrowht[2][0]{\addstackgap[.5\dimexpr#2\relax]{\vphantom{#1}}}
\newcommand{\unit}[1]{\ensuremath{\, \mathrm{#1}}}

\graphicspath{{images/}}

\title{Project Report}
\author{Nguyen Quy Khoi}
\date{30 June 2020}

\makeindex
\makeatletter
\let\thetitle\@title
\let\theauthor\@author
\let\thedate\@date
\makeatother

