\LoadClass{beamer}
%
% Choose how your presentation looks.
%
% For more themes, color themes and font themes, see:
% http://deic.uab.es/~iblanes/beamer_gallery/index_by_theme.html


\mode<presentation>
{
  \usetheme{CambridgeUS}
  \usecolortheme{default}
  \usefonttheme{professionalfonts}
  \setbeamertemplate{navigation symbols}{}
  \setbeamertemplate{caption}[numbered]
} 

%\usepackage{helvet}
\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{bm, listings, xcolor, matlab-prettifier}

%\renewcommand{\familydefault}{\sfdefault}
\newcommand{\vb}[2]{\vec{\bm{#1}}_{\bm{#2}}}
\newcommand{\ih}{\vec{\mathbf{i}}}
\newcommand{\jh}{\vec{\mathbf{j}}}
\newcommand{\kh}{\vec{\mathbf{k}}}

\title[Instructor: Dr. Nguyen Tan Tien]{Position Analysis}
\author[Khoi]{Nguyen Quy Khoi}
\institute[HCMUT-OISP-FME]{HCMUT-OISP - Faculty of Mechanical Engineering}
\date{20 February, 2020}
